name: Build Binaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [darwin, linux, windows]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64
          - os: linux
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: go build -o example-${{ matrix.os }}-${{ matrix.arch }} ./cmd/beatportdl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: beatportdl-${{ matrix.os }}-${{ matrix.arch }}
          path: beatportdl-${{ matrix.os }}-${{ matrix.arch }}
